### ISSUE TITLE
Troubles with Autodock Vina conda packages

### ISSUE THREAD

**Issue by leobiscassi** [bgruening/galaxytools#385]
Hi,
I've tried use early galaxy versions in the last few days to test the conda dependency solver, but I don't get success with this. In [Autodock Vina Tools](https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/autodock_vina), for instance, the vina program wasn't recognized. I have the follow configurations:

**dependency_resolvers_conf.xml**
```xml
<dependency_resolvers>
  <tool_shed_packages />
  <galaxy_packages />
  <galaxy_packages versionless="true" />
  <conda />
  <conda versionless="true" />
  <conda auto_install="true" />
  <conda auto_init="true" />
</dependency_resolvers>
```
**galaxy.ini**
```
# Set the default shell used by non-containerized jobs Galaxy-wide. This
# defaults to bash for all jobs and can be overidden at the destination
# level for heterogenous clusters. conda job resolution requires bash or zsh
# so if this is switched to /bin/sh for instance - conda resolution
# should be disabled. Containerized jobs always use /bin/sh - so more maximum
# portability tool authors should assume generated commands run in sh.
default_job_shell = /bin/bash
```

```
# The dependency resolves config file specifies an ordering and options for how
# Galaxy resolves tool dependencies (requirement tags in Tool XML). The default
# ordering is to the use the tool shed for tools installed that way, use local
# Galaxy packages, and then use conda if available.
# See https://github.com/galaxyproject/galaxy/blob/dev/doc/source/admin/dependency_resolvers.rst
# for more information on these options.
dependency_resolvers_config_file = config/dependency_resolvers_conf.xml

# Following conda dependeny resolution options are experimental as of early
# 2016. These will change the defaults for each conda resolver, but multiple
# resolvers can be configured independently and these options overridden in
# dependency_resolvers_config_file.
conda_prefix = tool-dependencies/_conda
# Override the conda executable to use, it will default to the one on the
# PATH (if available) and then to <conda_prefix>/bin/conda
conda_exec = /home/leobiscassi/miniconda2/bin/conda
# Pass debug flag to conda commands.
conda_debug = False
# conda channels to enable by default (http://conda.pydata.org/docs/custom-channels.html)
conda_ensure_channels = r,bioconda,iuc
# Set to True to instruct Galaxy to look for and install missing tool
# dependencies before each job runs.
conda_auto_install = True
# Set to True to instruct Galaxy to install conda from the web automatically
# if it cannot find a local copy and conda_exec is not configured.
conda_auto_init = True
```

After the first tool execution, galaxy creates the follow environments:

* __package__autodock-vina@__unversioned__
* __package__autodock-vina@__version__1.1.2
* __package__samtools@__unversioned__

All environments have the binaries programs, but apparently the environments aren't activated.

My currently conda install:

```yaml
Current conda install:

             platform : linux-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.21.9
       python version : 2.7.12.final.0
     requests version : 2.8.1
     root environment : /home/leobiscassi/miniconda2  (writable)
  default environment : /home/leobiscassi/miniconda2
     envs directories : /home/leobiscassi/miniconda2/envs
        package cache : /home/leobiscassi/miniconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.anaconda.org/bioconda/linux-64/
                        https://conda.anaconda.org/bioconda/noarch/
          config file : /home/leobiscassi/.condarc
         offline mode : False
    is foreign system : False
``` 
The galaxy message after running jobs is ```vina: command not found```, any suggestion about this?
The only documentation what I find about conda resolver is [here](https://docs.galaxyproject.org/en/master/admin/dependency_resolvers.html).

Thanks in advance.
